### ISSUE TITLE
A new docker tag of adop-jenkins that contains the latest and greatest updates

### ISSUE THREAD

**Issue by bzon** [Accenture/adop-jenkins#46]
It would be nice if there will be a docker tag that contains the latest and greatest such as `accenture/adop-jenkins:x.x.x-${jenkins_version}` that will be maintained on a separate branch.

My current project will use blue ocean and it will require a massive upgrade to all plugins. Any thoughts? @anton-kasperovich @nickdgriffin @kramos

**Comment by nickdgriffin** [comment]
I'd rather see us having release candidates for the next release rather than a tag that contains two indirectly related version numbers that will always change at the same time. I wouldn't want the "x.x.x" version to stay the same if the Jenkins version changes because everything in the image is coupled to the upstream Jenkins image.

If the verison of Jenkins is to be upgraded (which I'm all for) along with surrounding plugins then I'd see that as becoming "0.3.0-rc1" - that's what we did with the upgrade to Jenkins 2.x, and we maintained it on a separate branch so it could run in parallel to the main release whilst it was getting tested across everything.
